services:
   rsync_client:
      image: janpdev/rsyncbackup-client:v0.1
      container_name: rsyncbackup-client
      environment:
        - RSYNC_SERVER=${RSYNC_SERVER}
        - RSYNC_PORT=${RSYNC_PORT}
        - USER_NAME=${USER_NAME}
        - RSYNC_UID=${RSYNC_UID}
        - RSYNC_GID=${RSYNC_GID}
        - PUSH=${PUSH:-1}
        - SERVER_CONFIG_DIR=${SERVER_CONFIG_DIR:-/data/config}
        - SERVER_DATA_DIR=${SERVER_DATA_DIR:-/data/transfer_target}
      volumes:
        - type: bind
          source: ${KEY_DIR:-.}/sshkeys
          target: /data/sshkeys
        - type: bind
          source: ${SOURCE_DIR:-.}/data
          target: /upload
          read_only: true

