---
version: "2.1"
services:
  openssh-server:
    image:  janpdev/rsyncbackup-common:v0.1
    container_name: rsyncbackup-server-#USER_NAME#
    hostname: rsyncbackup-server-#USER_NAME#
    environment:
      - PUID=#RSYNC_UID#
      - PGID=#RSYNC_GID#
      - TZ=Etc/UTC
      - PUBLIC_KEY=#PUB_KEY#
      - SUDO_ACCESS=false 
      - USER_NAME=#USER_NAME
    volumes:
      - C:\nobackup\server\config:/config
      - C:\nobackup\server\transfer_target:/data
    ports:
      - #RSYNC_PORT#:2222
    restart: unless-stopped
