version: "3"
services:
  openssh-server:
    image: linuxserver/openssh-server:latest
    container_name: rsyncbackup-server
    hostname: rsyncbackup-server
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=Etc/UTC
      - PUBLIC_KEY_DIR=${PUBLIC_KEY_DIR:-./keys}
      - SUDO_ACCESS=false
      - USER_NAME=transfer
    volumes:
      - ${SERVER_CONFIG_DIR:-.}/config:/config
      - ${SERVER_DATA_DIR:-.}/data:/data
      - ${PUBLIC_KEY_DIR:-.}/keys:/keys
    ports:
      - ${RSYNC_PORT:-2222}:2222
    restart: unless-stopped


